@echo off
setlocal
set "GLM_SCRIPT=%~f0"
%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -EncodedCommand JAByAGEAdwA9AFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAGUAbgB2ADoARwBMAE0AXwBTAEMAUgBJAFAAVAApADsAIAAkAG0AYQByAGsAZQByAD0AWwByAGUAZwBlAHgAXQA6ADoATQBhAHQAYwBoACgAJAByAGEAdwAsACcAKAA/AG0AKQBeACMAIABHAEwATQBfAFAATwBXAEUAUgBTAEgARQBMAEwAXwBTAFQAQQBSAFQAXAByAD8AJAAnACkAOwAgAGkAZgAoAC0AbgBvAHQAIAAkAG0AYQByAGsAZQByAC4AUwB1AGMAYwBlAHMAcwApAHsAdABoAHIAbwB3ACAAJwBTAGMAcgBpAHAAdAAgAHAAYQB5AGwAbwBhAGQAIABpAHMAIABtAGkAcwBzAGkAbgBnACcAfQA7ACAAJABhAGMAdABpAG8AbgA9AFsAcwBjAHIAaQBwAHQAYgBsAG8AYwBrAF0AOgA6AEMAcgBlAGEAdABlACgAJAByAGEAdwAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABtAGEAcgBrAGUAcgAuAEkAbgBkAGUAeAArACQAbQBhAHIAawBlAHIALgBMAGUAbgBnAHQAaAApACkAOwAgACQAZQB4AGkAdABDAG8AZABlAD0AMAA7ACAAJAB0AHIAYQBuAHMAYwByAGkAcAB0AD0AJABmAGEAbABzAGUAOwAgAHQAcgB5ACAAewAgAGkAZgAoAFsAcwB0AHIAaQBuAGcAXQA6ADoASQBzAE4AdQBsAGwATwByAFcAaABpAHQAZQBTAHAAYQBjAGUAKAAkAGUAbgB2ADoARwBMAE0AXwBKAE8AQgBfAEwATwBHACkAKQAgAHsAIAAmACAAJABhAGMAdABpAG8AbgAgAH0AIABlAGwAcwBlACAAewAgAHQAcgB5ACAAewAgAFMAdABhAHIAdAAtAFQAcgBhAG4AcwBjAHIAaQBwAHQAIAAtAFAAYQB0AGgAIAAkAGUAbgB2ADoARwBMAE0AXwBKAE8AQgBfAEwATwBHACAALQBBAHAAcABlAG4AZAAgAC0ARgBvAHIAYwBlACAAfAAgAE8AdQB0AC0ATgB1AGwAbAA7ACAAJAB0AHIAYQBuAHMAYwByAGkAcAB0AD0AJAB0AHIAdQBlACAAfQAgAGMAYQB0AGMAaAAgAHsAIAB9ADsAIAAmACAAJABhAGMAdABpAG8AbgA7ACAAaQBmACgAJABMAEEAUwBUAEUAWABJAFQAQwBPAEQARQAgAC0AbgBlACAAMAApAHsAJABlAHgAaQB0AEMAbwBkAGUAPQAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFAH0AIAB9ACAAfQAgAGMAYQB0AGMAaAAgAHsAIAAkAG0AZQBzAHMAYQBnAGUAPQAkAF8AIAB8ACAATwB1AHQALQBTAHQAcgBpAG4AZwA7ACAAaQBmACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQAZQBuAHYAOgBHAEwATQBfAEoATwBCAF8ATABPAEcAKQApACAAewAgAFcAcgBpAHQAZQAtAE8AdQB0AHAAdQB0ACAAJABtAGUAcwBzAGEAZwBlACAAfQAgAGUAbABzAGUAaQBmACgALQBuAG8AdAAgACQAdAByAGEAbgBzAGMAcgBpAHAAdAApACAAewAgAFsASQBPAC4ARgBpAGwAZQBdADoAOgBBAHAAcABlAG4AZABBAGwAbABUAGUAeAB0ACgAJABlAG4AdgA6AEcATABNAF8ASgBPAEIAXwBMAE8ARwAsACQAbQBlAHMAcwBhAGcAZQApACAAfQA7ACAAJABlAHgAaQB0AEMAbwBkAGUAPQAxACAAfQAgAGYAaQBuAGEAbABsAHkAIAB7ACAAaQBmACgAJAB0AHIAYQBuAHMAYwByAGkAcAB0ACkAewB0AHIAeQAgAHsAIABTAHQAbwBwAC0AVAByAGEAbgBzAGMAcgBpAHAAdAAgAHwAIABPAHUAdAAtAE4AdQBsAGwAIAB9ACAAYwBhAHQAYwBoACAAewAgAH0AfQAgAH0AOwAgAGUAeABpAHQAIAAkAGUAeABpAHQAQwBvAGQAZQA=
set "GLM_EXIT=%ERRORLEVEL%"
echo Exit code: %GLM_EXIT%
exit /b %GLM_EXIT%
# GLM_POWERSHELL_START
# Game Library Manager · only the selected game containers are affected.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'Continue'
$dockerCommand = Get-Command docker.exe -ErrorAction SilentlyContinue; $dockerExecutable = if ($dockerCommand) { $dockerCommand.Source } else { Join-Path $env:ProgramFiles 'Docker\Docker\resources\bin\docker.exe' }
if (-not (Test-Path -LiteralPath $dockerExecutable -PathType Leaf)) { throw 'Docker Desktop is not installed. Install it, start Docker Desktop, then retry.' }
$env:PATH = (Split-Path -Parent $dockerExecutable) + [IO.Path]::PathSeparator + $env:PATH # Also resolves Docker Desktop's credential helper in this process only.
$operationId = if ([string]::IsNullOrWhiteSpace($env:GLM_INSTALL_OPERATION_ID)) { [guid]::NewGuid().ToString('N') } else { $env:GLM_INSTALL_OPERATION_ID }; if ($operationId -notmatch '^[A-Za-z0-9-]{8,64}$') { throw 'The install operation identity is invalid.' }
$destination = 'F:\backup\glm-native-recovery-20260909\install-proof\destination-bat-20260910-034731'; [void][IO.Directory]::CreateDirectory($destination); [void][IO.Directory]::CreateDirectory((Join-Path $destination '.gamelibrarymanager-locks'))
$nativeInstallLockHeld = $env:GLM_NATIVE_INSTALL_LOCK_HELD -eq '1'
function Test-NativeContainer { param([string]$name, [string]$expectedMetadata, [string]$expectedOperationId); try { $inspection = & $dockerExecutable container inspect $name --format '{{json .Config.Labels}}' 2>$null } catch { return $false }; $inspectExitCode = $LASTEXITCODE; if ($inspectExitCode -ne 0) { return $false }; try { $labels = (([string]($inspection | Out-String)).Trim() | ConvertFrom-Json) } catch { throw ('Refusing destructive cleanup for unowned container ' + $name + '.') }; $actualMetadata = [string]$labels.'com.gamelibrary.owner' + '|' + [string]$labels.'com.gamelibrary.game-id'; $actualOperationId = [string]$labels.'com.gamelibrary.operation-id'; if ($actualMetadata -cne $expectedMetadata -or ($expectedOperationId -and $actualOperationId -cne $expectedOperationId)) { throw ('Refusing destructive cleanup for unowned container ' + $name + '.') }; return $true }
function Enter-NativeInstallLock { param([string]$path); if ($nativeInstallLockHeld) { return $null }; $deadline = [DateTime]::UtcNow.AddHours(24); while ($true) { try { return [IO.FileStream]::new($path, [IO.FileMode]::OpenOrCreate, [IO.FileAccess]::ReadWrite, [IO.FileShare]::None, 1, [IO.FileOptions]::WriteThrough) } catch [IO.IOException] { if ([DateTime]::UtcNow -ge $deadline) { throw ('Timed out waiting for the selected game install lock: ' + $path) }; Start-Sleep -Milliseconds 250 } } }
function Exit-NativeInstallLock { param([IO.FileStream]$lock); if ($null -ne $lock) { $lock.Dispose() } }
$failedGames = [Collections.Generic.List[string]]::new()
Write-Output ((Get-Date -Format o) + ' GAME 1/1 · Downloading Gunbrella')
$installMutex = $null
try {
$installMutex = Enter-NativeInstallLock (Join-Path $destination '.gamelibrarymanager-locks\glm-87b8331f439a7c177f6f2994.lock')
$pullSuccess = $false; for ($attempt = 1; $attempt -le 5 -and -not $pullSuccess; $attempt++) {
  & $dockerExecutable info --format '{{.OSType}}' *> $null; if ($LASTEXITCODE -ne 0) { Write-Warning ('Docker is not ready; retry ' + $attempt + '/5'); Start-Sleep -Seconds ([Math]::Min($attempt * 2, 10)); continue }
  & $dockerExecutable pull 'michadockermisha/backup:gunbrella'; if ($LASTEXITCODE -eq 0) { $pullSuccess = $true } else { Write-Warning ('Pull failed for gunbrella on retry ' + $attempt + '/5'); if ($attempt -lt 5) { Start-Sleep -Seconds ([Math]::Min($attempt * 2, 10)) } }
}
if (-not $pullSuccess) { throw 'Docker pull failed for gunbrella after five attempts. Existing files were preserved.' }
$markerValue = 'GameLibraryManager|gunbrella|' + $operationId; $completionMarker = Join-Path $destination 'gunbrella-276e5335\.gamelibrarymanager-install-complete'; Remove-Item -LiteralPath $completionMarker -Force -ErrorAction SilentlyContinue
$runSuccess = $false; for ($attempt = 1; $attempt -le 3 -and -not $runSuccess; $attempt++) {
  Remove-Item -LiteralPath $completionMarker -Force -ErrorAction SilentlyContinue; if (Test-NativeContainer 'glm-87b8331f439a7c177f6f2994' 'native|gunbrella' $operationId) { & $dockerExecutable container rm --force 'glm-87b8331f439a7c177f6f2994' *> $null; if ($LASTEXITCODE -ne 0) { throw 'Could not remove the native container.' } }; & $dockerExecutable run --rm --name 'glm-87b8331f439a7c177f6f2994' --env ('GLM_INSTALL_OPERATION_ID=' + $operationId) --label 'com.gamelibrary.owner=native' --label 'com.gamelibrary.game-id=gunbrella' --label ('com.gamelibrary.operation-id=' + $operationId) --mount ("type=bind,source=$destination,target=/output") 'michadockermisha/backup:gunbrella' sh -c 'set -eu; mkdir -p ''/output/gunbrella-276e5335''; rm -f ''/output/gunbrella-276e5335/.gamelibrarymanager-install-complete''; copy_status=0; copy_output=$(cp -rL /home/. ''/output/gunbrella-276e5335/'' 2>&1) || copy_status=$?; if [ -n "$copy_output" ]; then printf ''%s\n'' "$copy_output" >&2; fi; if [ "$copy_status" -ne 0 ]; then if ! printf ''%s\n'' "$copy_output" | grep -Eiq ''(_Redist|preserve (permissions|mode)|permission denied|operation not permitted|I/O error|input/output error)'' || ! find ''/output/gunbrella-276e5335'' -mindepth 1 -print -quit | grep -q .; then exit "$copy_status"; fi; echo ''Continuing after a non-fatal Linux metadata-copy warning.'' >&2; fi; rm -f ''/output/gunbrella-276e5335/.gamelibrarymanager-install-complete''; find ''/output/gunbrella-276e5335'' -mindepth 1 -print -quit | grep -q .; du -sh ''/output/gunbrella-276e5335'' 2>/dev/null || true; marker_value=''GameLibraryManager|gunbrella|''$GLM_INSTALL_OPERATION_ID; printf ''%s\n'' "$marker_value" > ''/output/gunbrella-276e5335/.gamelibrarymanager-install-complete''; test -s ''/output/gunbrella-276e5335/.gamelibrarymanager-install-complete'''; $dockerRunExitCode = $LASTEXITCODE; $markerContent = if (Test-Path -LiteralPath $completionMarker -PathType Leaf) { Get-Content -LiteralPath $completionMarker -Raw -ErrorAction SilentlyContinue } else { '' }; if ($dockerRunExitCode -eq 0 -and ([string]$markerContent).Trim() -eq $markerValue) { $runSuccess = $true } else { Write-Warning ('Extraction failed for gunbrella on attempt ' + $attempt + '/3; the completion marker was not written or was invalid.'); if (Test-NativeContainer 'glm-87b8331f439a7c177f6f2994' 'native|gunbrella' $operationId) { & $dockerExecutable container rm --force 'glm-87b8331f439a7c177f6f2994' *> $null; if ($LASTEXITCODE -ne 0) { throw 'Could not remove the native container.' } }; if ($attempt -lt 3) { Start-Sleep -Seconds ([Math]::Min($attempt * 3, 15)) } }
}
if (-not $runSuccess) { throw 'Extraction failed for gunbrella after three attempts. Partial files were preserved; review the log and retry.' }
Write-Output ((Get-Date -Format o) + ' Completed gunbrella')
} catch { $failedGames.Add('gunbrella'); Write-Warning ('Failed gunbrella: ' + $_.Exception.Message) -WarningAction Continue } finally { Exit-NativeInstallLock $installMutex }
if ($failedGames.Count -gt 0) { throw ('Failed selected games: ' + ($failedGames -join ', ') + '. Other selected games were still attempted; review the per-game results before retrying.') }
Write-Output 'All selected operations completed.'
